default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: Callback_with_pg_development

test:
  <<: *default
  database: Callback_with_pg_test

production:
  <<: *default
  database: Callback_with_pg_production
  username: Callback_with_pg
  password: <%= ENV['Callback_WITH_PG_DATABASE_PASSWORD'] %>